//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMCDating.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public Like()
        {
            this.UsersLikes = new HashSet<UsersLike>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<UsersLike> UsersLikes { get; set; }
    }
}
