//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMCDating.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMCDatingEntities : DbContext
    {
        public MMCDatingEntities()
            : base("name=MMCDatingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Like> Likes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersLike> UsersLikes { get; set; }
        public DbSet<UsersContact> UsersContacts { get; set; }
        public DbSet<UsersMessage> UsersMessages { get; set; }
        public DbSet<UsersChat> UsersChats { get; set; }
        public DbSet<UsersLoginLog> UsersLoginLogs { get; set; }
        public DbSet<Location> Locations { get; set; }
    }
}
