//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMCDating.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLoginLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOutTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
